### PR TITLE
Allow for specifying a list of allowed users.

### PR DESCRIPTION
**Pull request by frankban**
By default, the current logic of allowing all controller users does not change.
But optionally an admin can specify the list of allowed users, so that not every container user will be able to use that specific jujushell instance.

### CODE REVIEW

**Comment by frankban** [comment]
QA:
- use this binary together with the charm proposed at https://github.com/juju/jujushell-charm/pull/7
- after deploying the local charm (providing the three required resources), follow the instructions at https://blog.jujugui.org/2018/01/03/accessing-the-juju-cli-from-within-the-gui/ in order to set up a working shell
- ensure the shell works with every controller user by default
- then allow only a couple of users and check that it works
- then disallow your user and check that you cannot start the sesssion
Thanks!

**Comment by mitechie** [comment]
I'm working on setting up to QA this but can I ask what this is for? I'm always hesitant any time user access is done user by user vs group management and I'm curious if there was a call for this or this is something we're predicting folks will want?

**Comment by mitechie** [comment]
In QA getting the error:

    Error talking to the terminal server: user "rick" is not allowed to access the service


I've set the config 

    juju config jujushell allowed-users
    rick, hatch

I then double checked the config and missed it was space separated. I updated it and retested it and it worked. 

I then revoked the permissions for rick and while it did not connect it did not get the nice error about rick not being allowed. It looks like it was in the console though so something with the GUI not picking it back up.

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by frankban** [comment]
Rick, thanks for the QA! We'll have to fix the GUI so that it handles error cases more gracefully.

**Pull request merged**
